Repository frenchbakery/dev_template, pull requests merged in 2023-02, with the labels that each got.

#1 Utils
  .devcontainer/Dockerfile
  .vscode/c_cpp_properties.json
  Makefile
Labels: enhancement

#6 Remote shell and start improvements
  Makefile
  README.md
Labels: enhancement

#5 Typos in README
  README.md
Labels: documentation

#7 fixed copying of include directory
  Makefile
Labels: bug
